services:
  - type: web
    name: whatsapp-baileys-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: AUTO_CONNECT
        value: "false"
