services:
  - type: web
    name: whatsapp-baileys-api
    env: node
    plan: free
    rootDir: .
    buildCommand: ./scripts/render-build.sh
    startCommand: ./scripts/render-start.sh
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: AUTO_CONNECT
        value: "false"
